# To run:
# RUN: `docker compose up -d`
# Set MONGO_URI inside `.env.` file as: MONGO_URI="mongodb://localhost:27017/issue-tracker"
name: 'issue-tracker-mongo'
services:
  mongo:
    image: mongo
    container_name: 'issue-tracker-mongo'
    command: mongod --quiet --logpath /dev/null 
    ports:
      - "27017:27017"
    volumes:
      - issue-tracker-data:/data/db
volumes:
  issue-tracker-data:
    driver: local